version: "3.1"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres